server:
  port: 9093
  servlet:
    context-path: /paymentSvc

spring:
  banner:
    location: bilqu-banner.txt

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      default-zone : http://localhost:8761/eureka
