server:
  port: 8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/vimalraj84/ms-retail-system/tree/main/config-repository